export const ADDTOCART = 'ADDTOCART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const INCREASECARTITEM = 'INCREASECARTITEM';
export const DECREASECARTITEM = 'DECREASECARTITEM';
export const INITCART = 'INITSTATE';